### PR TITLE
Menu for token payment #89

### PR DESCRIPTION
**Pull request by tschubotz**

### CODE REVIEW

**Comment by sche** [comment]
I think this should be a part of the token_payment general spec. Now intro part looks like duplicated here and there.

**Comment by tschubotz** [comment]
Well that's the thing. There is no token payment general spec. I though about putting everything into 1 spec. But then that spec would be huge ...

How would you do it?

**Comment by sche** [comment]
We could have a token_payment folder with general intro and links to subfolders with use-case specific screens. But in general use cases are different - like funds transfer or safe creation. So we could also have something like versioning in use cases and have a new version like "2.0-token-payment" for every use case. If a new feature influences some already existing flow, then possibly a new version of a spec should be added for that specific flow.
Or how do you think we could avoid duplications?

**Comment by tschubotz** [comment]
I'm not a fan of creating an extended structure with different versionings etc. since I don't see that it is worth the effort.

I don't mind creating a token_payment directory and the have different documents per flow. I think that would help, yes. Will do that.

**Comment by tschubotz** [comment]
merging this with #168

**Pull request closed without merging**
